[package]
org = "ballerinax"
name = "financial.swift.mt"
version = "3.0.3"
distribution = "2201.10.1"
authors=["Ballerina"]
keywords=["Financial", "SWIFT MT"]
repository="https://github.com/ballerina-platform/module-ballerinax-financial.swiftmt"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.prowidesoftware"
artifactId = "pw-swift-core"
version = "SRU2023-10.1.16"

# transitive dependency of com.prowidesoftware:pw-swift-core:SRU2023-10.1.16
[[platform.java17.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.12.0"

# transitive dependency of com.prowidesoftware:pw-swift-core:SRU2023-10.1.16
[[platform.java17.dependency]]
groupId = "com.google.code.gson"
artifactId = "gson"
version = "2.9.0"
